export const categories = [
  "Frameworks",
  "Styling",
  "Frontend Language",
  "Backend",
  "Programming Language",
  "Database",
  "Serverless",
  "Payments",
  "Containerization",
  "CI/CD",
  "Web Server",
  "Deployment",
  "Static Site Generation",
  "API",
  "Cross-platform Development",
  "Cloud Services",
  "Build Tools",
  "Microservices",
  "DevOps",
  "Security & Identity",
  "Realtime Database / Hosting",
  "User Experience Layer",
  "Scalable Architecture",
  "CMS",
  "Auth",
]
